# Generated by Django 3.0.6 on 2020-05-25 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(default=datetime.date.today)),
                ('test_start_date', models.DateTimeField()),
                ('test_end_date', models.DateTimeField()),
                ('test_timeframe', models.IntegerField()),
                ('test_result_target', models.CharField(max_length=15)),
                ('test_result_entry', models.CharField(max_length=15)),
                ('test_result_stockloss', models.CharField(max_length=15)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtesting.Stock')),
            ],
        ),
    ]
